name: Node CI

on:
    push:
        branches:
            - main
jobs:
    test-run-results:
        runs-on: ubuntu-latest
        environment: DEV
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node 16.0
              uses: actions/setup-node@v3
              with:
                node-version: 16

            - name: Install dependencies
              uses: bahmutov/npm-install@v1
              # env:
              #     CYPRESS_INSTALL_BINARY: 0

            # - name: Check Cypress cache
            #   run: |
            #       npx cypress cache path
            #       npx cypress cache list

            - name: restore / cache the binary
              id: cache-cypress
              uses: actions/cache@v1
              with:
                  path: ~/.cache/Cypress
                  key: >-
                      cypress-cache-v2-${{ runner.os }}-${{ hashFiles('**/package.json')
                      }}

            # - name: Install Dependencies
            #   continue-on-error: true
            #   run: npm ci
            - name: Run Cypress tests
              run:  |
              node ./helpers/qase-pre-script.js 
              npm run cy:run:ci node 
              ./helpers/qase-post-script.js


            # - name: Get Allure history
            #   uses: actions/checkout@v2
            #   if: always()
            #   continue-on-error: true
            #   with:
            #       ref: allure
            #       path: allure

            # - name: Generate Allure Report
            #   uses: simple-elf/allure-report-action@master
            #   if: always()
            #   with:
            #       allure_results: allure-results
            #       gh_pages: allure
            #       allure_history: allure-history
            #       keep_reports: 20

            # - name: Deploy report to Github Pages
            #   if: always()
            #   uses: peaceiris/actions-gh-pages@v3
            #   with:
            #       github_token: ${{ secrets.GITHUB_TOKEN }}
            #       publish_branch: allure
            #       publish_dir: allure-history 